### ISSUE TITLE
Too few arguments to function MASK\Mask\CodeGenerator\AbstractCodeGenerator::__construct()

### ISSUE THREAD

**Issue by kosimas** [IchHabRecht/mask_export#166]
HI,

since I updated mask from 5.0.0 to 5.1.1, I get this error in the Mask Export Backend View:

Oops, an error occurred!
Too few arguments to function MASK\Mask\CodeGenerator\AbstractCodeGenerator::__construct(), 0 passed in \typo3\sysext\core\Classes\Utility\GeneralUtility.php on line 3423 and exactly 1 expected

**Comment by kosimas** [comment]
Oh, I see you already fixed it 1e2cd5864f8b798fe28d8dc60353fe4ac3ed3bd7

**Comment by IchHabRecht** [comment]
Hi @kosimas,

Yes, I already addressed this problem in https://github.com/IchHabRecht/mask_export/commit/1e2cd5864f8b798fe28d8dc60353fe4ac3ed3bd7 and will release an new version. Thanks for the reminder ;-)
